"""autovote

Revision ID: b22ac0558b52
Revises: b4c086dbb499
Create Date: 2024-11-04 04:23:57.189508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22ac0558b52'
down_revision: Union[str, None] = 'b4c086dbb499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.add_column('post', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('post', sa.Column('published', sa.Boolean(), server_default='TRUE', nullable=False))
    op.add_column('post', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('post', 'content')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.add_column('post', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('post', 'created_at')
    op.drop_column('post', 'published')
    op.drop_column('post', 'price')
    op.drop_table('vote')
    # ### end Alembic commands ###
